import bcrypt from 'bcryptjs';

const password = 'admin';
const hash1 = '$2a$10$blLjYuLr7HZJfhcjiZ58Oee26jzyOFJunaTiGHvmBAiNHhLIETeLK'; // Used in SQL script
const hash2 = '$2a$10$ItqfP4aB6WBW04TU/Vea5.oDKHjA5byLfcK4sx4oZ9a4dZNqMzGem'; // Generated by reset-admin-force.js

async function verify() {
    console.log(`Checking password: "${password}"`);

    const match1 = await bcrypt.compare(password, hash1);
    console.log(`Hash 1 (SQL): ${match1 ? '✅ MATCH' : '❌ FAIL'}`);

    const match2 = await bcrypt.compare(password, hash2);
    console.log(`Hash 2 (Force): ${match2 ? '✅ MATCH' : '❌ FAIL'}`);
}

verify();
